import { withUpdater } from "../utils";

export const createAdminSlice = (set) => ({
  projectMgmtForm: { name: "", projectKey: "", description: "" },
  projectMgmtEditForm: { name: "", projectKey: "", description: "" },
  projectMgmtShowCreateModal: false,
  projectMgmtShowEditModal: false,
  projectMgmtEditingProjectId: null,
  userAdminName: "",
  userAdminEmail: "",
  userAdminPassword: "",
  userAdminRole: "member",
  userAdminShowCreateModal: false,
  userAdminShowEditModal: false,
  userAdminShowCreateGroupModal: false,
  userAdminShowEditGroupModal: false,
  userAdminEditingUserId: null,
  userAdminEditingGroupId: null,
  userAdminEditDraft: { name: "", email: "", password: "", role: "member" },
  userAdminGroupName: "",
  userAdminGroupMemberIds: [],
  userAdminEditGroupName: "",
  userAdminEditGroupMemberIds: [],
  setProjectMgmtForm: withUpdater(set, "projectMgmtForm"),
  setProjectMgmtEditForm: withUpdater(set, "projectMgmtEditForm"),
  setProjectMgmtShowCreateModal: withUpdater(set, "projectMgmtShowCreateModal"),
  setProjectMgmtShowEditModal: withUpdater(set, "projectMgmtShowEditModal"),
  setProjectMgmtEditingProjectId: withUpdater(set, "projectMgmtEditingProjectId"),
  setUserAdminName: withUpdater(set, "userAdminName"),
  setUserAdminEmail: withUpdater(set, "userAdminEmail"),
  setUserAdminPassword: withUpdater(set, "userAdminPassword"),
  setUserAdminRole: withUpdater(set, "userAdminRole"),
  setUserAdminShowCreateModal: withUpdater(set, "userAdminShowCreateModal"),
  setUserAdminShowEditModal: withUpdater(set, "userAdminShowEditModal"),
  setUserAdminShowCreateGroupModal: withUpdater(
    set,
    "userAdminShowCreateGroupModal",
  ),
  setUserAdminShowEditGroupModal: withUpdater(set, "userAdminShowEditGroupModal"),
  setUserAdminEditingUserId: withUpdater(set, "userAdminEditingUserId"),
  setUserAdminEditingGroupId: withUpdater(set, "userAdminEditingGroupId"),
  setUserAdminEditDraft: withUpdater(set, "userAdminEditDraft"),
  setUserAdminGroupName: withUpdater(set, "userAdminGroupName"),
  setUserAdminGroupMemberIds: withUpdater(set, "userAdminGroupMemberIds"),
  setUserAdminEditGroupName: withUpdater(set, "userAdminEditGroupName"),
  setUserAdminEditGroupMemberIds: withUpdater(set, "userAdminEditGroupMemberIds"),
});
