import { getStoredToken } from "../../api/client";
import { withUpdater } from "../utils";

export const createAppCoreSlice = (set) => ({
  token: getStoredToken(),
  authLoading: false,
  currentUser: null,
  users: [],
  userGroups: [],
  sprints: [],
  projects: [],
  projectSettings: null,
  columns: [],
  boardTotalsByStatus: {},
  backlogTasks: [],
  allTasks: [],
  sprintTasks: [],
  selectedSprintId: "",
  currentProjectId: "",
  loading: true,
  error: "",
  taskTitle: "",
  storyPoints: "",
  assigneeId: "",
  taskPriority: "medium",
  taskType: "task",
  taskLabel: "",
  taskVersion: "",
  showCreateTaskModal: false,
  showFilterModal: false,
  showAssigneeOverflow: false,
  confirmDialog: {
    open: false,
    title: "",
    message: "",
    confirmLabel: "Confirm",
  },
  taskBundle: null,
  activeView: "dashboard",
  dashboardAssignedTasks: [],
  filters: {
    assigneeId: "",
    priority: "",
    label: "",
    status: "",
    type: "",
    search: "",
  },
  filterDraft: {
    sprintId: "",
    priority: "",
    label: "",
    status: "",
    type: "",
  },
  setToken: withUpdater(set, "token"),
  setAuthLoading: withUpdater(set, "authLoading"),
  setCurrentUser: withUpdater(set, "currentUser"),
  setUsers: withUpdater(set, "users"),
  setUserGroups: withUpdater(set, "userGroups"),
  setSprints: withUpdater(set, "sprints"),
  setProjects: withUpdater(set, "projects"),
  setProjectSettings: withUpdater(set, "projectSettings"),
  setColumns: withUpdater(set, "columns"),
  setBoardTotalsByStatus: withUpdater(set, "boardTotalsByStatus"),
  setBacklogTasks: withUpdater(set, "backlogTasks"),
  setAllTasks: withUpdater(set, "allTasks"),
  setSprintTasks: withUpdater(set, "sprintTasks"),
  setSelectedSprintId: withUpdater(set, "selectedSprintId"),
  setCurrentProjectId: withUpdater(set, "currentProjectId"),
  setLoading: withUpdater(set, "loading"),
  setError: withUpdater(set, "error"),
  setTaskTitle: withUpdater(set, "taskTitle"),
  setStoryPoints: withUpdater(set, "storyPoints"),
  setAssigneeId: withUpdater(set, "assigneeId"),
  setTaskPriority: withUpdater(set, "taskPriority"),
  setTaskType: withUpdater(set, "taskType"),
  setTaskLabel: withUpdater(set, "taskLabel"),
  setTaskVersion: withUpdater(set, "taskVersion"),
  setShowCreateTaskModal: withUpdater(set, "showCreateTaskModal"),
  setShowFilterModal: withUpdater(set, "showFilterModal"),
  setShowAssigneeOverflow: withUpdater(set, "showAssigneeOverflow"),
  setConfirmDialog: withUpdater(set, "confirmDialog"),
  setTaskBundle: withUpdater(set, "taskBundle"),
  setActiveView: withUpdater(set, "activeView"),
  setDashboardAssignedTasks: withUpdater(set, "dashboardAssignedTasks"),
  setFilters: withUpdater(set, "filters"),
  setFilterDraft: withUpdater(set, "filterDraft"),
});
