import { withUpdater } from "../utils";

export const createPlanningSlice = (set) => ({
  boardDragState: { taskId: "", sourceStatus: "", overStatus: "" },
  boardRecentlyMovedTaskId: "",
  boardBlockedStatus: "",
  boardBlockedStatusesDuringDrag: new Set(),
  boardAllowedStatusesDuringDrag: new Set(),
  backlogShowCreateSprintModal: false,
  backlogExpandedKeys: new Set(["backlog"]),
  backlogCreateDraft: { name: "", startDate: "", endDate: "" },
  backlogCreateNameError: "",
  backlogSprintCompleteDialog: null,
  backlogSprintDeleteDialog: null,
  backlogSprintDeleteError: "",
  backlogDragState: { taskId: "", sourceKey: "", overKey: "" },
  backlogRecentlyMovedTaskId: "",
  backlogBlockedDropKey: "",
  sprintMgmtCreateDraft: { name: "", startDate: "", endDate: "" },
  sprintMgmtEditDraft: {
    name: "",
    startDate: "",
    endDate: "",
    status: "planned",
  },
  sprintMgmtEditingSprintId: null,
  sprintMgmtSelectedBacklogTaskIds: [],
  sprintMgmtIsDropActive: false,
  sprintMgmtShowCreateModal: false,
  setBoardDragState: withUpdater(set, "boardDragState"),
  setBoardRecentlyMovedTaskId: withUpdater(set, "boardRecentlyMovedTaskId"),
  setBoardBlockedStatus: withUpdater(set, "boardBlockedStatus"),
  setBoardBlockedStatusesDuringDrag: withUpdater(
    set,
    "boardBlockedStatusesDuringDrag",
  ),
  setBoardAllowedStatusesDuringDrag: withUpdater(
    set,
    "boardAllowedStatusesDuringDrag",
  ),
  setBacklogShowCreateSprintModal: withUpdater(set, "backlogShowCreateSprintModal"),
  setBacklogExpandedKeys: withUpdater(set, "backlogExpandedKeys"),
  setBacklogCreateDraft: withUpdater(set, "backlogCreateDraft"),
  setBacklogCreateNameError: withUpdater(set, "backlogCreateNameError"),
  setBacklogSprintCompleteDialog: withUpdater(set, "backlogSprintCompleteDialog"),
  setBacklogSprintDeleteDialog: withUpdater(set, "backlogSprintDeleteDialog"),
  setBacklogSprintDeleteError: withUpdater(set, "backlogSprintDeleteError"),
  setBacklogDragState: withUpdater(set, "backlogDragState"),
  setBacklogRecentlyMovedTaskId: withUpdater(set, "backlogRecentlyMovedTaskId"),
  setBacklogBlockedDropKey: withUpdater(set, "backlogBlockedDropKey"),
  setSprintMgmtCreateDraft: withUpdater(set, "sprintMgmtCreateDraft"),
  setSprintMgmtEditDraft: withUpdater(set, "sprintMgmtEditDraft"),
  setSprintMgmtEditingSprintId: withUpdater(set, "sprintMgmtEditingSprintId"),
  setSprintMgmtSelectedBacklogTaskIds: withUpdater(
    set,
    "sprintMgmtSelectedBacklogTaskIds",
  ),
  setSprintMgmtIsDropActive: withUpdater(set, "sprintMgmtIsDropActive"),
  setSprintMgmtShowCreateModal: withUpdater(set, "sprintMgmtShowCreateModal"),
});
