import { withUpdater } from "../utils";

export const createSettingsSlice = (set) => ({
  settingsForm: null,
  settingsMemberIds: [],
  settingsSavingSettings: false,
  settingsSavingMembers: false,
  settingsActiveTab: "users",
  settingsWorkflowFromKey: "",
  settingsWorkflowToKey: "",
  settingsShowAddStageModal: false,
  settingsNewStageDraft: {
    name: "",
    counterGroup: "",
    afterKey: "__start_of_group__",
  },
  settingsNewLabel: "",
  settingsNewType: "",
  settingsNewVersion: "",
  settingsShowAddLabelModal: false,
  settingsShowAddTypeModal: false,
  settingsShowAddVersionModal: false,
  settingsStageMigrations: {},
  settingsStageDeleteDialog: null,
  settingsStageDragState: {
    fromIndex: -1,
    fromKey: "",
    fromGroup: "",
    overIndex: -1,
  },
  settingsAllowedDropIndexes: new Set(),
  settingsBlockedDropIndexes: new Set(),
  settingsBlockedDropReason: "",
  setSettingsForm: withUpdater(set, "settingsForm"),
  setSettingsMemberIds: withUpdater(set, "settingsMemberIds"),
  setSettingsSavingSettings: withUpdater(set, "settingsSavingSettings"),
  setSettingsSavingMembers: withUpdater(set, "settingsSavingMembers"),
  setSettingsActiveTab: withUpdater(set, "settingsActiveTab"),
  setSettingsWorkflowFromKey: withUpdater(set, "settingsWorkflowFromKey"),
  setSettingsWorkflowToKey: withUpdater(set, "settingsWorkflowToKey"),
  setSettingsShowAddStageModal: withUpdater(set, "settingsShowAddStageModal"),
  setSettingsNewStageDraft: withUpdater(set, "settingsNewStageDraft"),
  setSettingsNewLabel: withUpdater(set, "settingsNewLabel"),
  setSettingsNewType: withUpdater(set, "settingsNewType"),
  setSettingsNewVersion: withUpdater(set, "settingsNewVersion"),
  setSettingsShowAddLabelModal: withUpdater(set, "settingsShowAddLabelModal"),
  setSettingsShowAddTypeModal: withUpdater(set, "settingsShowAddTypeModal"),
  setSettingsShowAddVersionModal: withUpdater(set, "settingsShowAddVersionModal"),
  setSettingsStageMigrations: withUpdater(set, "settingsStageMigrations"),
  setSettingsStageDeleteDialog: withUpdater(set, "settingsStageDeleteDialog"),
  setSettingsStageDragState: withUpdater(set, "settingsStageDragState"),
  setSettingsAllowedDropIndexes: withUpdater(set, "settingsAllowedDropIndexes"),
  setSettingsBlockedDropIndexes: withUpdater(set, "settingsBlockedDropIndexes"),
  setSettingsBlockedDropReason: withUpdater(set, "settingsBlockedDropReason"),
});
