"use client"
// Auto-generated by `npx boneyard-js build` — do not edit
import { registerBones } from 'boneyard-js'

import _backlog_view from './backlog-view.bones.json'
import _projects_management_view from './projects-management-view.bones.json'
import _app_settings_view from './app-settings-view.bones.json'
import _summary_view from './summary-view.bones.json'

registerBones({
  "backlog-view": _backlog_view,
  "projects-management-view": _projects_management_view,
  "app-settings-view": _app_settings_view,
  "summary-view": _summary_view,
})
